# print('press 1 for add')
# print('press 2 for subtract')
# print('press 3 for multiply')
# print('press 4 for divide')
# choice=(int(input('enter ur choice:')))

# v=int(input("enter first number"))
# a=int(input("enter secong number"))

# def add():
#     print(v+a)

# def sub():
#     print(v-a)

# def multi():
#     print(v*a)

# def div():
#     print(v/a)

# if choice == 1:
#     add()
# elif choice==2:
#     sub()
# elif choice==3:
#     multi()
# elif choice==4:
#       div()  

# print("press 1 for add")
# print("press 2 for subtract")
# print("press 3 for multi")
# print("press 4 for div")

# a=int(input("enter first number:"))
# b=int(input("enter second number:"))

# choice=int(input("enter your choice number :"))

# def add():
#     print(a+b)

# def sub():
#     print(a-b)
# def multi():
#     print(a*b)
# def div():
#     print(a/b)

# if choice==1:
#     add()
# elif choice==2: 
#     sub()
# elif choice==3:
#      multi()
# elif choice==4:
#     div()

# print("press 1 for add")
# print("press 2 for sub")
# print("press 3 for multi")
# print("press 4 for div")


# choice=int(input("enter your choice number"))
# a=int(input("enter first number"))
# b=int(input("enter second number"))

# def add(a,b):
#     print(a+b)
# def sub():
#     print(a-b)
# def multi():
#     print(a*b)
# def div():            
#     print(a/b)

# if choice==1:
#     add()
# elif choice==2:
#     sub()
# elif choice==3:
#     multi()
# elif choice():
#     div()




# parameter 

# def user(a,b):
#     print(a*b)
# user(10,5)    


# def user(v,t):
#     print(v**t)
# user(100,5)

# def user(a,b):
#     print(a/b)
# user(20,5)    

# def hello(a,b):
#    print(a%b)
# hello(50,6)


# print="press 1 for add option :" 
# print="press 2 for subtract option :"
# print= "press 3 for multi option :"
# print= "press 4 for div option :"


# choice=int(input("enter your choice option"))
# a=int(input("enter your first digits"))
# b=int(input("enter second digit"))

# def add():
#     print(a+b)
# def sub():
#     print(a-b)
# def multi():
#     print(a*b)
# def div():
#     print (a/b)
# if choice==1:
#    add()
# elif choice==2:
#     sub()
# elif choice==3:
#     multi ()

# elif choice==4:
#     div()

# # def user(a,b):
# #     print(a+b)
# # user(20,5)   
# 
# 
# 
# 
# while True:
#     print("press * main meinu")
#     print("press 1 for withdraw")
#     print("press 2 for balance")
#     print("press 3 for deposit")
#     print("press 4 for enquiry")

#     choice=int(input("enter your number:"))

#     if choice==1:
#         print("withdraw")
#     elif choice==2:
#         print("balance")
#     elif choice==3:
#       


# print("press 1 for add")
# print("press 2 for subtract")
# print("press 3 for multi")
# print ("press 4 for div")

# choice=int(input("enter your choice number"))

# v=int(input("enter your first number"))
# b=int(input("enter your second number"))

# def add():
#     print(v+b)

# def sub():
#     print(v-b)

# def multi():
#     print(v*b)
# def div():
#     print(v/b)


# if choice==1:
#     add()
# elif choice==2:
#     sub()
# elif choice==3:
#     multi()
# elif choice==4:
#     div()            


# # parameter
# def add(a,b):
#     print(a+b)
# add(20,10)    

# def f1():
#     return "Welcome in Prepbytes"
# print(f1())



